import { NextResponse } from "next/server";
import { neon } from "@neondatabase/serverless";

const sql = neon(process.env.DATABASE_URL!);

const CATEGORIAS = [
  { nombre: "4TA Caballeros", orden: 1 },
  { nombre: "5TA Damas", orden: 2 },
  { nombre: "5TA Caballeros", orden: 3 },
  { nombre: "6TA Damas", orden: 4 },
  { nombre: "6TA Caballeros", orden: 5 },
  { nombre: "7MA Damas", orden: 6 },
  { nombre: "7MA Caballeros", orden: 7 },
  { nombre: "8VA Damas", orden: 8 },
  { nombre: "8VA Caballeros", orden: 9 },
  { nombre: "SUMA 8", orden: 10 },
];

// Formato: APELLIDO NOMBRE|LOCALIDAD
const JUGADORES_CSV = {
  "8VA Damas": `RODRIGUEZ TIZIANA|ARENALES
DIEHL FLORENCIA|ARENALES
RENATA AGUERO|ARENALES
ANTONELA FENOGLIO|ARENALES
LAVAGNINO CARINA|ARENALES
LUCIA MEDINA|ARENALES
PAGANI MARIANELA|ARENALES
VIOLETA MONDINO|ARENALES
LASERNA MELINA|ARENALES
FLORENCIA APEZ|ARENALES
CAROLINA GONZALEZ|ARRIBEÑOS
MARIA HEREDIA|ARRIBEÑOS
GISELA CUADRO|ARRIBEÑOS
VALENTINA CHIPONI|ARRIBEÑOS
FLAVIA SAURO|ARRIBEÑOS
SUBIRADA NOELIA|ARRIBEÑOS
GUTIERREZ GABRIELA|ARRIBEÑOS
MARTINA ROMERO|ARRIBEÑOS
MARISEL VALDEMORO|ARRIBEÑOS
MILJOVICEVICH JENNIFER|ARRIBEÑOS
VALDEMORO LAURA|ARRIBEÑOS
GABRIELA GARCIA|ARRIBEÑOS
RAMBAUD YESICA|ARRIBEÑOS
CANTELMI BETIANA|ARRIBEÑOS
DI SANTO GISELA|ASCENSION
PATRICIA MARTINI|ASCENSION
DAIANA ALVAREZ|ASCENSION
ROCIO LIBORIO|ASCENSION
HERRERA MARIA PAULA|ASCENSION
GIACHELO MARILU|ASCENSION
NOELIA SUAREZ|ASCENSION
COMINO MARIA JOSE|ASCENSION
ZULMA ULLUA|ASCENSION
LAURA SAMORA|ASCENSION
CAROLINA CEJAS|ASCENSION
NORALI GARCIA|ASCENSION
OTTONE AGUSTINA|ASCENSION
LUDMILA FERRE|FERRE
CRUZ VICTORIA|FERRE
BONIFACIO MARISOL|FERRE
DEBORA BARROSO|FERRE
ERICA PAGELA|FERRE
POLICANI ANA PAULA|FERRE
GIANCANE ALFONSINA|FERRE
CIELO CORONEL|FERRE
QUIROGA MARIANELA|FERRE
ORIANA TROMBINI|FERRE
VILCHE DAIANA|FERRE
FISHINI LARA|FERRE
MARTINA FUENTES|FERRE
LAURA SALVATORE|FERRE
NATALIA GIL|FERRE
LORENA POLERI|FERRE
MARISA CALDERONE|FERRE
ADRIANA VILLAFAÑE|FERRE
ANALIA RECAGNO|FERRE
GILDA DI PRINZIO|FERRE
SABINA BAVA|FERRE
SOFIA ANDRIOLI|FERRE
PAULA SAYAGO|FERRE
CAROLINA GAUNA|FERRE
DAFNE MEDINA|FERRE
FLORENCIA BENITEZ|FERRE
HERNANDEZ ESTELA|FERRE
MARIA BRAVO|FERRE
MARTINA SANNA|FERRE
NATALIA GHIOTTI|FERRE
VICTORIA SANNA|FERRE
CENTENO ELIZABETH|JUNIN
FERREYRA ELIANA|JUNIN
VARGAS MELANY|LA ANGELITA
YAMILA MOHANA|LA ANGELITA
FATIMA MOHANA|LA ANGELITA
MARCELA POLLITELO|LINCOLN
CINTIA CENTENO|MARIA TERESA
VANESA ESTEVEZ|MARIA TERESA
POMPEI EVA|SANTA ISABEL
MARTINA PEÑA|TEODELINA
MILAGROS CUBELLS|TEODELINA
CANALI MICAELA|VEDIA
CAREN ACOSTA|VEDIA
GUINI LOPEZ|VEDIA
NAIR REYNOSO|VEDIA
YAMILA JAURENA|VEDIA
DANIELA CREGO|VEDIA`,

  "5TA Damas": `ADRIANA VILLAFAÑE|FERRE
IRIGOYEN NADIA|ARRIBEÑOS
VALENTINA CHIPONI|ARRIBEÑOS
VANESA ESTEVEZ|MARIA TERESA
LEGUIZAMON CANDELA|FERRE
DANIELA CREGO|VEDIA
CAROLINA CEJAS|ASCENSION
BETIANA FERNANDEZ|ASCENSION
ROCIO LIBORIO|ASCENSION
GARCIA NOELIA|ASCENSION
HERRERA MARIA PAULA|ASCENSION
RENATA AGUERO|ARENALES
LUCIA MEDINA|ARENALES
RODRIGUEZ TIZIANA|ARENALES
CENTENO ELIZABETH|JUNIN
FERREYRA ELIANA|JUNIN
PAULA SAYAGO|FERRE
MARIANELA BANEGA|FERRE
ANALIA RECAGNO|FERRE
CAROLINA GAUNA|FERRE
SOFIA ANDRIOLI|FERRE
MIRAGLIA CAROLINA|TEODELINA
SABINA BAVA|FERRE
MARIA BRAVO|FERRE
ORIANA TROMBINI|FERRE
MARIA GOMEZ|FERRE
ALVAREZ ELIANA|FERRE`,

  "5TA Caballeros": `GOMEZ DIEGO|FERRE
NESCIER MARIANO|FERRE
CELMAN LUCIANO|FERRE
FACUNDO ALMIRON|FERRE
BARROSO DIEGO|FERRE
GONZALEZ TOBIAS|FERRE
CRISTIAN GIACHELLO|ASCENSION
EZEQUIEL COSTAMAGNA|ASCENSION
ALEJANDRO COSTAMAGNA|ASCENSION
BRUNO PEREA|ASCENSION
DANIEL GIMENEZ|ASCENSION
JUAN PABLO GIACHELLO|ASCENSION
FACUNDO VEGA|ARENALES
ALEJO LARROCA|ARENALES
JULIO OJEDA|TEODELINA
LUCAS MIRAGLIA|TEODELINA
FERRERO MARTIN|ARRIBEÑOS
FRANCO CHIPONI|ARRIBEÑOS
MARIANO ORTIZ|ARRIBEÑOS
TOMAS MACIEL|ARRIBEÑOS
GERMAN VALDIVIEZO|ARRIBEÑOS
MAURO REYNOSO|VEDIA
GONZALO CREGO|VEDIA
MATIAS PIAGGIO|VEDIA
GIMENEZ FRANCO|VEDIA
URIEL MORETTO|VEDIA
SERGIO SANCHEZ|VEDIA`,

  "4TA Caballeros": `MARTIN ROMERO|ARRIBEÑOS
NAHUEL CARDOZO|ARRIBEÑOS
CRISTIAN SERRU|ARRIBEÑOS
LUCIANO CALVO|FERRE
BARROSO DIEGO|FERRE
CRISTIAN GIACHELLO|ASCENSION
EZEQUIEL COSTAMAGNA|ASCENSION`,

  "6TA Damas": `DIEHL FLORENCIA|ARENALES
LAVAGNINO CARINA|ARENALES
FLORENCIA APEZ|ARENALES
LIDIA PONCE|ARENALES
FLAVIA SAURO|ARRIBEÑOS
GISELA CUADRO|ARRIBEÑOS
MILJOVICEVICH JENNIFER|ARRIBEÑOS
SUBIRADA NOELIA|ARRIBEÑOS
GABRIELA GARCIA|ARRIBEÑOS
VALDEMORO LAURA|ARRIBEÑOS
RAMBAUD YESICA|ARRIBEÑOS
CANTELMI BETIANA|ARRIBEÑOS
MARISEL VALDEMORO|ARRIBEÑOS
PATRICIA MARTINI|ASCENSION
DI SANTO GISELA|ASCENSION
DAIANA ALVAREZ|ASCENSION
GIACHELO MARILU|ASCENSION
NOELIA SUAREZ|ASCENSION
COMINO MARIA JOSE|ASCENSION
ZULMA ULLUA|ASCENSION
LAURA SAMORA|ASCENSION
NORALI GARCIA|ASCENSION
OTTONE AGUSTINA|ASCENSION
LUDMILA FERRE|FERRE
CRUZ VICTORIA|FERRE
BONIFACIO MARISOL|FERRE
DEBORA BARROSO|FERRE
ERICA PAGELA|FERRE
POLICANI ANA PAULA|FERRE
GIANCANE ALFONSINA|FERRE
CIELO CORONEL|FERRE
QUIROGA MARIANELA|FERRE
VILCHE DAIANA|FERRE
FISHINI LARA|FERRE
LAURA SALVATORE|FERRE
NATALIA GIL|FERRE
LORENA POLERI|FERRE
MARISA CALDERONE|FERRE
GILDA DI PRINZIO|FERRE
DAFNE MEDINA|FERRE
FLORENCIA BENITEZ|FERRE
HERNANDEZ ESTELA|FERRE
MARTINA SANNA|FERRE
NATALIA GHIOTTI|FERRE
VICTORIA SANNA|FERRE
VARGAS MELANY|LA ANGELITA
YAMILA MOHANA|LA ANGELITA
FATIMA MOHANA|LA ANGELITA
MARCELA POLLITELO|LINCOLN
CINTIA CENTENO|MARIA TERESA
POMPEI EVA|SANTA ISABEL
MARTINA PEÑA|TEODELINA
MILAGROS CUBELLS|TEODELINA
CANALI MICAELA|VEDIA
CAREN ACOSTA|VEDIA
GUINI LOPEZ|VEDIA
NAIR REYNOSO|VEDIA
YAMILA JAURENA|VEDIA`,

  "SUMA 8": `ADRIANA VILLAFAÑE|FERRE
IRIGOYEN NADIA|ARRIBEÑOS
VALENTINA CHIPONI|ARRIBEÑOS
VANESA ESTEVEZ|MARIA TERESA
LEGUIZAMON CANDELA|FERRE
DANIELA CREGO|VEDIA
GOMEZ DIEGO|FERRE
NESCIER MARIANO|FERRE
CELMAN LUCIANO|FERRE
FACUNDO ALMIRON|FERRE
BARROSO DIEGO|FERRE
GONZALEZ TOBIAS|FERRE`,

  "8VA Caballeros": `FACUNDO VEGA|ARENALES
ALEJO LARROCA|ARENALES
LEONEL ALTAMIRANO|ARENALES
HERRERO JOAQUIN|ARENALES
JOEL MEDINA|ARENALES
MARTIN ROMERO|ARRIBEÑOS
NAHUEL CARDOZO|ARRIBEÑOS
CRISTIAN SERRU|ARRIBEÑOS
FERRERO MARTIN|ARRIBEÑOS
FRANCO CHIPONI|ARRIBEÑOS
MARIANO ORTIZ|ARRIBEÑOS
TOMAS MACIEL|ARRIBEÑOS
GERMAN VALDIVIEZO|ARRIBEÑOS
FACUNDO VEGA|ASCENSION
DANIEL GIMENEZ|ASCENSION
JUAN PABLO GIACHELLO|ASCENSION
ALEJANDRO COSTAMAGNA|ASCENSION
BRUNO PEREA|ASCENSION
CRISTIAN GIACHELLO|ASCENSION
EZEQUIEL COSTAMAGNA|ASCENSION
LUCIANO CALVO|FERRE
GOMEZ DIEGO|FERRE
BARROSO DIEGO|FERRE
FACUNDO ALMIRON|FERRE
GONZALEZ TOBIAS|FERRE
CELMAN LUCIANO|FERRE
BENJAMIN PINTO|FERRE
NESCIER MARIANO|FERRE
FEDERICO HEREDIA|JUNIN
KEVIN HEREDIA|JUNIN
EDUARDO HEREDIA|JUNIN
MAXIMILIANO HEREDIA|JUNIN
GONZALO CREGO|VEDIA
MAURO REYNOSO|VEDIA
MATIAS PIAGGIO|VEDIA
GIMENEZ FRANCO|VEDIA
URIEL MORETTO|VEDIA
SERGIO SANCHEZ|VEDIA
JULIO OJEDA|TEODELINA
LUCAS MIRAGLIA|TEODELINA`,

  "7MA Caballeros": `HERRERO JOAQUIN|ARENALES
JOEL MEDINA|ARENALES
LEONEL ALTAMIRANO|ARENALES
LUCIANO CALVO|FERRE
BENJAMIN PINTO|FERRE
FACUNDO VEGA|ASCENSION
FEDERICO HEREDIA|JUNIN
KEVIN HEREDIA|JUNIN
EDUARDO HEREDIA|JUNIN
MAXIMILIANO HEREDIA|JUNIN`,

  "7MA Damas": `ANTONELA FENOGLIO|ARENALES
PAGANI MARIANELA|ARENALES
VIOLETA MONDINO|ARENALES
LASERNA MELINA|ARENALES
CAROLINA GONZALEZ|ARRIBEÑOS
MARIA HEREDIA|ARRIBEÑOS
GUTIERREZ GABRIELA|ARRIBEÑOS
MARTINA ROMERO|ARRIBEÑOS
MARTINA FUENTES|FERRE`,

  "6TA Caballeros": `FACUNDO VEGA|ARENALES
ALEJO LARROCA|ARENALES
LEONEL ALTAMIRANO|ARENALES
HERRERO JOAQUIN|ARENALES
JOEL MEDINA|ARENALES
MARTIN ROMERO|ARRIBEÑOS
NAHUEL CARDOZO|ARRIBEÑOS
CRISTIAN SERRU|ARRIBEÑOS
FERRERO MARTIN|ARRIBEÑOS
FRANCO CHIPONI|ARRIBEÑOS
MARIANO ORTIZ|ARRIBEÑOS
TOMAS MACIEL|ARRIBEÑOS
GERMAN VALDIVIEZO|ARRIBEÑOS
FACUNDO VEGA|ASCENSION
DANIEL GIMENEZ|ASCENSION
JUAN PABLO GIACHELLO|ASCENSION
ALEJANDRO COSTAMAGNA|ASCENSION
BRUNO PEREA|ASCENSION
CRISTIAN GIACHELLO|ASCENSION
EZEQUIEL COSTAMAGNA|ASCENSION
LUCIANO CALVO|FERRE
GOMEZ DIEGO|FERRE
BARROSO DIEGO|FERRE
FACUNDO ALMIRON|FERRE
GONZALEZ TOBIAS|FERRE
CELMAN LUCIANO|FERRE
BENJAMIN PINTO|FERRE
NESCIER MARIANO|FERRE
FEDERICO HEREDIA|JUNIN
KEVIN HEREDIA|JUNIN
EDUARDO HEREDIA|JUNIN
MAXIMILIANO HEREDIA|JUNIN
GONZALO CREGO|VEDIA
MAURO REYNOSO|VEDIA
MATIAS PIAGGIO|VEDIA
GIMENEZ FRANCO|VEDIA
URIEL MORETTO|VEDIA
SERGIO SANCHEZ|VEDIA
JULIO OJEDA|TEODELINA
LUCAS MIRAGLIA|TEODELINA`,
};

function parseJugadorLine(line: string): { nombre: string; apellido: string; localidad: string } | null {
  const trimmed = line.trim();
  if (!trimmed) return null;

  const parts = trimmed.split("|");
  if (parts.length !== 2) return null;

  const nombreCompleto = parts[0].trim();
  const localidad = parts[1].trim();

  const palabras = nombreCompleto.split(" ");
  if (palabras.length < 2) return null;

  // El apellido es la primera palabra, el resto es el nombre
  const apellido = palabras[0];
  const nombre = palabras.slice(1).join(" ");

  return { nombre, apellido, localidad };
}

export async function POST() {
  try {
    if (process.env.ADMIN_IMPORT_VERANO_ENABLED !== "true") {
      return NextResponse.json({ error: "No disponible" }, { status: 404 });
    }
    console.log("[v0] Starting import process...");
    
    let categoriasInserted = 0;
    let jugadoresInserted = 0;
    let jugadoresSkipped = 0;

    // Step 1: Insert categories sequentially
    console.log("[v0] Inserting categories...");
    for (const cat of CATEGORIAS) {
      try {
        const existing = await sql`SELECT id FROM categorias WHERE nombre = ${cat.nombre}`;
        if (existing.length === 0) {
          await sql`
            INSERT INTO categorias (nombre, orden_nivel)
            VALUES (${cat.nombre}, ${cat.orden})
          `;
          categoriasInserted++;
          console.log(`[v0] Inserted category: ${cat.nombre}`);
        }
      } catch (error) {
        console.log(`[v0] Error with category ${cat.nombre}:`, error);
      }
    }

    // Step 2: Get category IDs
    const categoriesMap: Record<string, number> = {};
    for (const cat of CATEGORIAS) {
      const result = await sql`SELECT id FROM categorias WHERE nombre = ${cat.nombre}`;
      if (result.length > 0) {
        categoriesMap[cat.nombre] = result[0].id as number;
      }
    }

    console.log("[v0] Categories map:", categoriesMap);

    // Step 3: Insert players one by one with delay
    console.log("[v0] Starting to insert players...");
    
    for (const [categoriaNombre, csvData] of Object.entries(JUGADORES_CSV)) {
      const categoriaId = categoriesMap[categoriaNombre];
      if (!categoriaId) {
        console.log(`[v0] Category not found: ${categoriaNombre}`);
        continue;
      }

      const lines = csvData.split("\n");
      console.log(`[v0] Processing ${lines.length} players for ${categoriaNombre}...`);

      for (let i = 0; i < lines.length; i++) {
        const jugadorData = parseJugadorLine(lines[i]);
        if (!jugadorData) continue;

        const { nombre, apellido, localidad } = jugadorData;

        try {
          // Check if exists
          const existing = await sql`
            SELECT id FROM jugadores 
            WHERE LOWER(nombre) = LOWER(${nombre}) 
            AND LOWER(apellido) = LOWER(${apellido})
          `;

          if (existing.length === 0) {
            // Determine gender based on category name
            const genero = categoriaNombre.includes("Damas") ? "femenino" : "masculino";

            await sql`
              INSERT INTO jugadores (nombre, apellido, localidad, genero, categoria_actual_id, puntos_totales, estado)
              VALUES (${nombre}, ${apellido}, ${localidad}, ${genero}, ${categoriaId}, 0, 'activo')
            `;
            jugadoresInserted++;
            
            if ((jugadoresInserted + jugadoresSkipped) % 25 === 0) {
              console.log(`[v0] Progress: ${jugadoresInserted} inserted, ${jugadoresSkipped} skipped`);
            }
          } else {
            jugadoresSkipped++;
          }
        } catch (error) {
          console.log(`[v0] Error inserting ${nombre} ${apellido}:`, error);
          jugadoresSkipped++;
        }

        // Small delay every 10 inserts to avoid overwhelming the DB
        if (i % 10 === 0 && i > 0) {
          await new Promise(resolve => setTimeout(resolve, 100));
        }
      }
    }

    console.log("[v0] Import completed successfully");
    console.log(`[v0] Final stats - Categories: ${categoriasInserted}, Players inserted: ${jugadoresInserted}, Players skipped: ${jugadoresSkipped}`);

    return NextResponse.json({
      success: true,
      stats: {
        categorias: categoriasInserted,
        jugadores: jugadoresInserted,
        jugadoresSkipped: jugadoresSkipped,
      },
    });
  } catch (error) {
    console.error("[v0] Import failed:", error);
    return NextResponse.json(
      { error: "Failed to import data", details: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    );
  }
}
