
ALTER TABLE partidos_zona 
ADD COLUMN IF NOT EXISTS set1_tiebreak VARCHAR(10),
ADD COLUMN IF NOT EXISTS set2_tiebreak VARCHAR(10),
ADD COLUMN IF NOT EXISTS set3_tiebreak VARCHAR(10);

ALTER TABLE llaves 
ADD COLUMN IF NOT EXISTS set1_tiebreak VARCHAR(10),
ADD COLUMN IF NOT EXISTS set2_tiebreak VARCHAR(10),
ADD COLUMN IF NOT EXISTS set3_tiebreak VARCHAR(10);
